development:
  db:
    host: 0.0.0.0
    database: sentimeta_simple_api
  fapi_stage: staging
  fapi_prefix: 'http://5.9.0.5/api/v1'
  token: '123'
test:
  db:
    host: 0.0.0.0
    database: sentimeta_simple_api_test
  fapi_stage: staging
  fapi_prefix: 'http://5.9.0.5/api/v1'
  token: '123'
